DROP TABLE IF EXISTS ItemType CASCADE;
DROP TABLE IF EXISTS Item CASCADE; 
DROP TABLE IF EXISTS PartsList CASCADE; 
DROP TABLE IF EXISTS Vendor CASCADE; 
DROP TABLE IF EXISTS VendorItem CASCADE; 
DROP TABLE IF EXISTS ItemToVendorItemMap CASCADE; 